# Automatically generated qmake file, created by the Introjucer
# Don't edit this file! Your changes will be overwritten when you re-save the Introjucer project!

TEMPLATE = app
CONFIG  -= qt
CONFIG  += warn_off

CONFIG(release, debug|release){
    DESTDIR     = build/release/
    OBJECTS_DIR = build/release/intermediate/
    TARGET = WindowTestProject
}
CONFIG(debug, debug|release){
    DESTDIR     = build/debug/
    OBJECTS_DIR = build/debug/intermediate/
    TARGET = WindowTestProject
}

# Compiler flags
QMAKE_CXXFLAGS = -std=c++11 -Wall
unix:  QMAKE_CXXFLAGS += -I/usr/include/freetype2 -I/usr/include `pkg-config --cflags alsa freetype2 libcurl x11 xext xinerama` -pthread -DLINUX=1
win32: QMAKE_CXXFLAGS += -mstackrealign -D__MINGW__=1 -D__MINGW_EXTENSION=

QMAKE_CXXFLAGS_DEBUG   = -g -ggdb  -O0
CONFIG(debug, debug|release){
    INCLUDEPATH = \
        ../../JuceLibraryCode \
        ../../../../SDKs/JuceLibrary/4.3.1/modules \

    DEFINES += \ 
        "DEBUG=1" \ 
        "_DEBUG=1" \ 
        "JUCER_QT_CREATOR_D5F46ABF=1" \ 
        "JUCE_APP_VERSION=1.0.0" \ 
        "JUCE_APP_VERSION_HEX=0x10000" \ 

}

QMAKE_CXXFLAGS_RELEASE =  -O3
CONFIG(release, debug|release){
    INCLUDEPATH = \
        ../../JuceLibraryCode \
        ../../../../SDKs/JuceLibrary/4.3.1/modules \

    DEFINES += \ 
        "NDEBUG=1" \ 
        "JUCER_QT_CREATOR_D5F46ABF=1" \ 
        "JUCE_APP_VERSION=1.0.0" \ 
        "JUCE_APP_VERSION_HEX=0x10000" \ 

}


QMAKE_CFLAGS         = $$QMAKE_CXXFLAGS
QMAKE_CFLAGS_RELEASE = $$QMAKE_CXXFLAGS_RELEASE
QMAKE_CFLAGS_DEBUG   = $$QMAKE_CXXFLAGS_DEBUG


# Linker flags
LIBS = -L$$DESTDIR 
unix:  LIBS += -L/usr/X11R6/lib/ `pkg-config --libs alsa freetype2 libcurl x11 xext xinerama` -lGL -ldl -lpthread -lrt
win32: LIBS += -lgdi32 -luser32 -lkernel32 -lcomctl32 -lcomdlg32 -limm32 -lole32 -loleaut32 -lopengl32 -lrpcrt4 -lshlwapi -luuid -lversion -lwininet -lwinmm -lws2_32 -lwsock32 -static -lpthread
win32: QMAKE_LFLAGS += -static-libstdc++ -static-libgcc
QMAKE_LFLAGS += 
QMAKE_LFLAGS_DEBUG += -fvisibility=hidden

# Source and header files
SOURCES = \
	"../../Source/MainComponent.cpp" \
	"../../Source/Main.cpp" \
	"../../JuceLibraryCode/juce_audio_basics.cpp" \
	"../../JuceLibraryCode/juce_audio_devices.cpp" \
	"../../JuceLibraryCode/juce_audio_formats.cpp" \
	"../../JuceLibraryCode/juce_audio_processors.cpp" \
	"../../JuceLibraryCode/juce_core.cpp" \
	"../../JuceLibraryCode/juce_cryptography.cpp" \
	"../../JuceLibraryCode/juce_data_structures.cpp" \
	"../../JuceLibraryCode/juce_events.cpp" \
	"../../JuceLibraryCode/juce_graphics.cpp" \
	"../../JuceLibraryCode/juce_gui_basics.cpp" \
	"../../JuceLibraryCode/juce_gui_extra.cpp" \
	"../../JuceLibraryCode/juce_opengl.cpp" \
	"../../JuceLibraryCode/juce_video.cpp" \


HEADERS = \
	"../../Source/MainComponent.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_basics/buffers/juce_AudioChannelSet.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_basics/buffers/juce_AudioDataConverters.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_basics/buffers/juce_AudioSampleBuffer.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_basics/buffers/juce_FloatVectorOperations.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_basics/effects/juce_CatmullRomInterpolator.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_basics/effects/juce_Decibels.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_basics/effects/juce_FFT.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_basics/effects/juce_IIRFilter.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_basics/effects/juce_LagrangeInterpolator.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_basics/effects/juce_LinearSmoothedValue.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_basics/effects/juce_Reverb.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_basics/midi/juce_MidiBuffer.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_basics/midi/juce_MidiFile.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_basics/midi/juce_MidiKeyboardState.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_basics/midi/juce_MidiMessage.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_basics/midi/juce_MidiMessageSequence.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_basics/midi/juce_MidiRPN.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_basics/mpe/juce_MPEInstrument.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_basics/mpe/juce_MPEMessages.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_basics/mpe/juce_MPENote.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_basics/mpe/juce_MPESynthesiser.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_basics/mpe/juce_MPESynthesiserBase.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_basics/mpe/juce_MPESynthesiserVoice.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_basics/mpe/juce_MPEValue.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_basics/mpe/juce_MPEZone.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_basics/mpe/juce_MPEZoneLayout.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_basics/sources/juce_AudioSource.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_basics/sources/juce_BufferingAudioSource.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_basics/sources/juce_ChannelRemappingAudioSource.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_basics/sources/juce_IIRFilterAudioSource.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_basics/sources/juce_MixerAudioSource.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_basics/sources/juce_PositionableAudioSource.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_basics/sources/juce_ResamplingAudioSource.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_basics/sources/juce_ReverbAudioSource.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_basics/sources/juce_ToneGeneratorAudioSource.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_basics/synthesisers/juce_Synthesiser.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_basics/juce_audio_basics.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_basics/juce_audio_basics.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_devices/audio_io/juce_AudioDeviceManager.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_devices/audio_io/juce_AudioIODevice.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_devices/audio_io/juce_AudioIODeviceType.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_devices/audio_io/juce_SystemAudioVolume.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_devices/midi_io/juce_MidiInput.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_devices/midi_io/juce_MidiMessageCollector.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_devices/midi_io/juce_MidiOutput.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_devices/native/juce_MidiDataConcatenator.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_devices/sources/juce_AudioSourcePlayer.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_devices/sources/juce_AudioTransportSource.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_devices/juce_audio_devices.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_devices/juce_audio_devices.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_formats/codecs/flac/libFLAC/include/private/all.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_formats/codecs/flac/libFLAC/include/private/bitmath.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_formats/codecs/flac/libFLAC/include/private/bitreader.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_formats/codecs/flac/libFLAC/include/private/bitwriter.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_formats/codecs/flac/libFLAC/include/private/cpu.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_formats/codecs/flac/libFLAC/include/private/crc.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_formats/codecs/flac/libFLAC/include/private/fixed.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_formats/codecs/flac/libFLAC/include/private/float.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_formats/codecs/flac/libFLAC/include/private/format.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_formats/codecs/flac/libFLAC/include/private/lpc.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_formats/codecs/flac/libFLAC/include/private/md5.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_formats/codecs/flac/libFLAC/include/private/memory.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_formats/codecs/flac/libFLAC/include/private/metadata.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_formats/codecs/flac/libFLAC/include/private/stream_encoder.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_formats/codecs/flac/libFLAC/include/private/stream_encoder_framing.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_formats/codecs/flac/libFLAC/include/private/window.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_formats/codecs/flac/libFLAC/include/protected/all.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_formats/codecs/flac/libFLAC/include/protected/stream_decoder.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_formats/codecs/flac/libFLAC/include/protected/stream_encoder.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_formats/codecs/flac/all.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_formats/codecs/flac/alloc.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_formats/codecs/flac/assert.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_formats/codecs/flac/callback.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_formats/codecs/flac/compat.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_formats/codecs/flac/endswap.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_formats/codecs/flac/export.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_formats/codecs/flac/format.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_formats/codecs/flac/metadata.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_formats/codecs/flac/ordinals.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_formats/codecs/flac/stream_decoder.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_formats/codecs/flac/stream_encoder.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_formats/codecs/flac/win_utf8_io.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/books/coupled/res_books_51.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/books/coupled/res_books_stereo.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/books/floor/floor_books.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/books/uncoupled/res_books_uncoupled.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/modes/floor_all.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/modes/psych_8.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/modes/psych_11.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/modes/psych_16.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/modes/psych_44.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/modes/residue_8.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/modes/residue_16.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/modes/residue_44.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/modes/residue_44p51.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/modes/residue_44u.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/modes/setup_8.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/modes/setup_11.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/modes/setup_16.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/modes/setup_22.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/modes/setup_32.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/modes/setup_44.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/modes/setup_44p51.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/modes/setup_44u.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/modes/setup_X.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/backends.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/bitrate.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/codebook.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/codec_internal.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/envelope.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/highlevel.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/lookup.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/lookup_data.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/lpc.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/lsp.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/masking.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/mdct.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/misc.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/os.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/psy.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/registry.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/scales.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/smallft.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/window.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_formats/codecs/oggvorbis/codec.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_formats/codecs/oggvorbis/config_types.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_formats/codecs/oggvorbis/ogg.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_formats/codecs/oggvorbis/os_types.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_formats/codecs/oggvorbis/vorbisenc.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_formats/codecs/oggvorbis/vorbisfile.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_formats/codecs/juce_AiffAudioFormat.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_formats/codecs/juce_CoreAudioFormat.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_formats/codecs/juce_FlacAudioFormat.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_formats/codecs/juce_LAMEEncoderAudioFormat.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_formats/codecs/juce_MP3AudioFormat.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_formats/codecs/juce_OggVorbisAudioFormat.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_formats/codecs/juce_QuickTimeAudioFormat.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_formats/codecs/juce_WavAudioFormat.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_formats/codecs/juce_WindowsMediaAudioFormat.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_formats/format/juce_AudioFormat.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_formats/format/juce_AudioFormatManager.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_formats/format/juce_AudioFormatReader.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_formats/format/juce_AudioFormatReaderSource.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_formats/format/juce_AudioFormatWriter.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_formats/format/juce_AudioSubsectionReader.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_formats/format/juce_BufferingAudioFormatReader.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_formats/format/juce_MemoryMappedAudioFormatReader.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_formats/sampler/juce_Sampler.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_formats/juce_audio_formats.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_formats/juce_audio_formats.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_processors/format/juce_AudioPluginFormat.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_processors/format/juce_AudioPluginFormatManager.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_processors/format_types/juce_AU_Shared.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_processors/format_types/juce_AudioUnitPluginFormat.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_processors/format_types/juce_LADSPAPluginFormat.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_processors/format_types/juce_VST3Common.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_processors/format_types/juce_VST3Headers.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_processors/format_types/juce_VST3PluginFormat.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_processors/format_types/juce_VSTCommon.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_processors/format_types/juce_VSTInterface.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_processors/format_types/juce_VSTMidiEventList.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_processors/format_types/juce_VSTPluginFormat.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_processors/processors/juce_AudioPlayHead.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_processors/processors/juce_AudioPluginInstance.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_processors/processors/juce_AudioProcessor.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_processors/processors/juce_AudioProcessorEditor.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_processors/processors/juce_AudioProcessorGraph.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_processors/processors/juce_AudioProcessorListener.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_processors/processors/juce_AudioProcessorParameter.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_processors/processors/juce_GenericAudioProcessorEditor.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_processors/processors/juce_PluginDescription.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_processors/scanning/juce_KnownPluginList.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_processors/scanning/juce_PluginDirectoryScanner.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_processors/scanning/juce_PluginListComponent.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_processors/utilities/juce_AudioParameterBool.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_processors/utilities/juce_AudioParameterChoice.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_processors/utilities/juce_AudioParameterFloat.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_processors/utilities/juce_AudioParameterInt.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_processors/utilities/juce_AudioProcessorParameterWithID.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_processors/utilities/juce_AudioProcessorValueTreeState.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_processors/juce_audio_processors.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_audio_processors/juce_audio_processors.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/containers/juce_AbstractFifo.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/containers/juce_Array.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/containers/juce_ArrayAllocationBase.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/containers/juce_DynamicObject.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/containers/juce_ElementComparator.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/containers/juce_HashMap.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/containers/juce_LinkedListPointer.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/containers/juce_ListenerList.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/containers/juce_NamedValueSet.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/containers/juce_OwnedArray.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/containers/juce_PropertySet.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/containers/juce_ReferenceCountedArray.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/containers/juce_ScopedValueSetter.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/containers/juce_SortedSet.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/containers/juce_SparseSet.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/containers/juce_Variant.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/files/juce_DirectoryIterator.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/files/juce_File.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/files/juce_FileFilter.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/files/juce_FileInputStream.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/files/juce_FileOutputStream.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/files/juce_FileSearchPath.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/files/juce_MemoryMappedFile.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/files/juce_TemporaryFile.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/files/juce_WildcardFileFilter.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/javascript/juce_Javascript.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/javascript/juce_JSON.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/logging/juce_FileLogger.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/logging/juce_Logger.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/maths/juce_BigInteger.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/maths/juce_Expression.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/maths/juce_MathsFunctions.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/maths/juce_NormalisableRange.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/maths/juce_Random.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/maths/juce_Range.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/maths/juce_StatisticsAccumulator.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/memory/juce_Atomic.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/memory/juce_ByteOrder.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/memory/juce_ContainerDeletePolicy.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/memory/juce_HeapBlock.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/memory/juce_LeakedObjectDetector.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/memory/juce_Memory.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/memory/juce_MemoryBlock.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/memory/juce_OptionalScopedPointer.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/memory/juce_ReferenceCountedObject.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/memory/juce_ScopedPointer.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/memory/juce_SharedResourcePointer.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/memory/juce_Singleton.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/memory/juce_WeakReference.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/misc/juce_Result.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/misc/juce_RuntimePermissions.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/misc/juce_Uuid.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/misc/juce_WindowsRegistry.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/native/juce_android_JNIHelpers.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/native/juce_BasicNativeHeaders.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/native/juce_mac_ClangBugWorkaround.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/native/juce_osx_ObjCHelpers.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/native/juce_posix_SharedCode.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/native/juce_win32_ComSmartPtr.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/network/juce_IPAddress.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/network/juce_MACAddress.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/network/juce_NamedPipe.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/network/juce_Socket.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/network/juce_URL.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/network/juce_WebInputStream.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/streams/juce_BufferedInputStream.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/streams/juce_FileInputSource.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/streams/juce_InputSource.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/streams/juce_InputStream.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/streams/juce_MemoryInputStream.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/streams/juce_MemoryOutputStream.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/streams/juce_OutputStream.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/streams/juce_SubregionStream.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/system/juce_CompilerSupport.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/system/juce_PlatformDefs.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/system/juce_StandardHeader.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/system/juce_SystemStats.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/system/juce_TargetPlatform.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/text/juce_Base64.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/text/juce_CharacterFunctions.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/text/juce_CharPointer_ASCII.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/text/juce_CharPointer_UTF8.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/text/juce_CharPointer_UTF16.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/text/juce_CharPointer_UTF32.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/text/juce_Identifier.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/text/juce_LocalisedStrings.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/text/juce_NewLine.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/text/juce_String.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/text/juce_StringArray.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/text/juce_StringPairArray.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/text/juce_StringPool.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/text/juce_StringRef.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/text/juce_TextDiff.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/threads/juce_ChildProcess.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/threads/juce_CriticalSection.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/threads/juce_DynamicLibrary.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/threads/juce_HighResolutionTimer.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/threads/juce_InterProcessLock.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/threads/juce_Process.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/threads/juce_ReadWriteLock.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/threads/juce_ScopedLock.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/threads/juce_ScopedReadLock.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/threads/juce_ScopedWriteLock.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/threads/juce_SpinLock.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/threads/juce_Thread.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/threads/juce_ThreadLocalValue.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/threads/juce_ThreadPool.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/threads/juce_TimeSliceThread.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/threads/juce_WaitableEvent.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/time/juce_PerformanceCounter.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/time/juce_RelativeTime.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/time/juce_Time.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/unit_tests/juce_UnitTest.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/xml/juce_XmlDocument.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/xml/juce_XmlElement.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/zip/zlib/crc32.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/zip/zlib/deflate.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/zip/zlib/inffast.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/zip/zlib/inffixed.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/zip/zlib/inflate.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/zip/zlib/inftrees.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/zip/zlib/trees.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/zip/zlib/zconf.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/zip/zlib/zconf.in.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/zip/zlib/zlib.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/zip/zlib/zutil.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/zip/juce_GZIPCompressorOutputStream.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/zip/juce_GZIPDecompressorInputStream.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/zip/juce_ZipFile.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/juce_core.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_core/juce_core.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_cryptography/encryption/juce_BlowFish.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_cryptography/encryption/juce_Primes.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_cryptography/encryption/juce_RSAKey.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_cryptography/hashing/juce_MD5.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_cryptography/hashing/juce_SHA256.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_cryptography/hashing/juce_Whirlpool.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_cryptography/juce_cryptography.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_cryptography/juce_cryptography.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_data_structures/app_properties/juce_ApplicationProperties.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_data_structures/app_properties/juce_PropertiesFile.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_data_structures/undomanager/juce_UndoableAction.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_data_structures/undomanager/juce_UndoManager.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_data_structures/values/juce_CachedValue.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_data_structures/values/juce_Value.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_data_structures/values/juce_ValueTree.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_data_structures/values/juce_ValueTreeSynchroniser.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_data_structures/juce_data_structures.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_data_structures/juce_data_structures.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_events/broadcasters/juce_ActionBroadcaster.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_events/broadcasters/juce_ActionListener.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_events/broadcasters/juce_AsyncUpdater.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_events/broadcasters/juce_ChangeBroadcaster.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_events/broadcasters/juce_ChangeListener.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_events/interprocess/juce_ConnectedChildProcess.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_events/interprocess/juce_InterprocessConnection.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_events/interprocess/juce_InterprocessConnectionServer.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_events/messages/juce_ApplicationBase.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_events/messages/juce_CallbackMessage.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_events/messages/juce_DeletedAtShutdown.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_events/messages/juce_Initialisation.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_events/messages/juce_Message.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_events/messages/juce_MessageListener.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_events/messages/juce_MessageManager.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_events/messages/juce_MountedVolumeListChangeDetector.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_events/messages/juce_NotificationType.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_events/native/juce_osx_MessageQueue.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_events/native/juce_ScopedXLock.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_events/native/juce_win32_HiddenMessageWindow.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_events/timers/juce_MultiTimer.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_events/timers/juce_Timer.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_events/juce_events.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_events/juce_events.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_graphics/colour/juce_Colour.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_graphics/colour/juce_ColourGradient.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_graphics/colour/juce_Colours.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_graphics/colour/juce_FillType.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_graphics/colour/juce_PixelFormats.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_graphics/contexts/juce_GraphicsContext.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_graphics/contexts/juce_LowLevelGraphicsContext.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_graphics/contexts/juce_LowLevelGraphicsPostScriptRenderer.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_graphics/contexts/juce_LowLevelGraphicsSoftwareRenderer.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_graphics/effects/juce_DropShadowEffect.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_graphics/effects/juce_GlowEffect.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_graphics/effects/juce_ImageEffectFilter.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_graphics/fonts/juce_AttributedString.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_graphics/fonts/juce_CustomTypeface.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_graphics/fonts/juce_Font.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_graphics/fonts/juce_GlyphArrangement.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_graphics/fonts/juce_TextLayout.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_graphics/fonts/juce_Typeface.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_graphics/geometry/juce_AffineTransform.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_graphics/geometry/juce_BorderSize.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_graphics/geometry/juce_EdgeTable.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_graphics/geometry/juce_Line.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_graphics/geometry/juce_Path.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_graphics/geometry/juce_PathIterator.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_graphics/geometry/juce_PathStrokeType.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_graphics/geometry/juce_Point.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_graphics/geometry/juce_Rectangle.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_graphics/geometry/juce_RectangleList.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_graphics/image_formats/jpglib/cderror.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_graphics/image_formats/jpglib/jchuff.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_graphics/image_formats/jpglib/jconfig.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_graphics/image_formats/jpglib/jdct.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_graphics/image_formats/jpglib/jdhuff.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_graphics/image_formats/jpglib/jerror.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_graphics/image_formats/jpglib/jinclude.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_graphics/image_formats/jpglib/jmemsys.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_graphics/image_formats/jpglib/jmorecfg.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_graphics/image_formats/jpglib/jpegint.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_graphics/image_formats/jpglib/jpeglib.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_graphics/image_formats/jpglib/jversion.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_graphics/image_formats/jpglib/transupp.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_graphics/image_formats/pnglib/png.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_graphics/image_formats/pnglib/pngconf.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_graphics/image_formats/pnglib/pnginfo.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_graphics/image_formats/pnglib/pngpriv.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_graphics/image_formats/pnglib/pngstruct.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_graphics/images/juce_Image.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_graphics/images/juce_ImageCache.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_graphics/images/juce_ImageConvolutionKernel.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_graphics/images/juce_ImageFileFormat.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_graphics/native/juce_mac_CoreGraphicsContext.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_graphics/native/juce_mac_CoreGraphicsHelpers.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_graphics/native/juce_RenderingHelpers.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_graphics/placement/juce_Justification.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_graphics/placement/juce_RectanglePlacement.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_graphics/juce_graphics.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_graphics/juce_graphics.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/application/juce_Application.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/buttons/juce_ArrowButton.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/buttons/juce_Button.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/buttons/juce_DrawableButton.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/buttons/juce_HyperlinkButton.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/buttons/juce_ImageButton.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/buttons/juce_ShapeButton.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/buttons/juce_TextButton.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/buttons/juce_ToggleButton.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/buttons/juce_ToolbarButton.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/commands/juce_ApplicationCommandID.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/commands/juce_ApplicationCommandInfo.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/commands/juce_ApplicationCommandManager.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/commands/juce_ApplicationCommandTarget.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/commands/juce_KeyPressMappingSet.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/components/juce_CachedComponentImage.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/components/juce_Component.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/components/juce_ComponentListener.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/components/juce_Desktop.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/components/juce_ModalComponentManager.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/drawables/juce_Drawable.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/drawables/juce_DrawableComposite.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/drawables/juce_DrawableImage.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/drawables/juce_DrawablePath.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/drawables/juce_DrawableRectangle.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/drawables/juce_DrawableShape.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/drawables/juce_DrawableText.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/filebrowser/juce_DirectoryContentsDisplayComponent.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/filebrowser/juce_DirectoryContentsList.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/filebrowser/juce_FileBrowserComponent.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/filebrowser/juce_FileBrowserListener.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/filebrowser/juce_FileChooser.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/filebrowser/juce_FileChooserDialogBox.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/filebrowser/juce_FileListComponent.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/filebrowser/juce_FilenameComponent.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/filebrowser/juce_FilePreviewComponent.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/filebrowser/juce_FileSearchPathListComponent.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/filebrowser/juce_FileTreeComponent.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/filebrowser/juce_ImagePreviewComponent.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/keyboard/juce_CaretComponent.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/keyboard/juce_KeyboardFocusTraverser.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/keyboard/juce_KeyListener.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/keyboard/juce_KeyPress.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/keyboard/juce_ModifierKeys.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/keyboard/juce_SystemClipboard.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/keyboard/juce_TextEditorKeyMapper.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/keyboard/juce_TextInputTarget.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/layout/juce_AnimatedPosition.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/layout/juce_AnimatedPositionBehaviours.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/layout/juce_ComponentAnimator.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/layout/juce_ComponentBoundsConstrainer.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/layout/juce_ComponentBuilder.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/layout/juce_ComponentMovementWatcher.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/layout/juce_ConcertinaPanel.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/layout/juce_FlexBox.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/layout/juce_FlexItem.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/layout/juce_GroupComponent.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/layout/juce_MultiDocumentPanel.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/layout/juce_ResizableBorderComponent.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/layout/juce_ResizableCornerComponent.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/layout/juce_ResizableEdgeComponent.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/layout/juce_ScrollBar.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/layout/juce_StretchableLayoutManager.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/layout/juce_StretchableLayoutResizerBar.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/layout/juce_StretchableObjectResizer.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/layout/juce_TabbedButtonBar.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/layout/juce_TabbedComponent.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/layout/juce_Viewport.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/lookandfeel/juce_LookAndFeel.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/lookandfeel/juce_LookAndFeel_V1.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/lookandfeel/juce_LookAndFeel_V2.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/lookandfeel/juce_LookAndFeel_V3.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/menus/juce_MenuBarComponent.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/menus/juce_MenuBarModel.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/menus/juce_PopupMenu.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/misc/juce_BubbleComponent.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/misc/juce_DropShadower.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/mouse/juce_ComponentDragger.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/mouse/juce_DragAndDropContainer.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/mouse/juce_DragAndDropTarget.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/mouse/juce_FileDragAndDropTarget.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/mouse/juce_LassoComponent.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/mouse/juce_MouseCursor.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/mouse/juce_MouseEvent.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/mouse/juce_MouseInactivityDetector.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/mouse/juce_MouseInputSource.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/mouse/juce_MouseListener.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/mouse/juce_SelectedItemSet.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/mouse/juce_TextDragAndDropTarget.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/mouse/juce_TooltipClient.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/native/juce_MultiTouchMapper.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/positioning/juce_MarkerList.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/positioning/juce_RelativeCoordinate.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/positioning/juce_RelativeCoordinatePositioner.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/positioning/juce_RelativeParallelogram.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/positioning/juce_RelativePoint.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/positioning/juce_RelativePointPath.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/positioning/juce_RelativeRectangle.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/properties/juce_BooleanPropertyComponent.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/properties/juce_ButtonPropertyComponent.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/properties/juce_ChoicePropertyComponent.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/properties/juce_PropertyComponent.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/properties/juce_PropertyPanel.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/properties/juce_SliderPropertyComponent.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/properties/juce_TextPropertyComponent.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/widgets/juce_ComboBox.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/widgets/juce_ImageComponent.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/widgets/juce_Label.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/widgets/juce_ListBox.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/widgets/juce_ProgressBar.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/widgets/juce_Slider.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/widgets/juce_TableHeaderComponent.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/widgets/juce_TableListBox.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/widgets/juce_TextEditor.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/widgets/juce_Toolbar.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/widgets/juce_ToolbarItemComponent.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/widgets/juce_ToolbarItemFactory.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/widgets/juce_ToolbarItemPalette.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/widgets/juce_TreeView.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/windows/juce_AlertWindow.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/windows/juce_CallOutBox.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/windows/juce_ComponentPeer.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/windows/juce_DialogWindow.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/windows/juce_DocumentWindow.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/windows/juce_NativeMessageBox.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/windows/juce_ResizableWindow.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/windows/juce_ThreadWithProgressWindow.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/windows/juce_TooltipWindow.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/windows/juce_TopLevelWindow.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/juce_gui_basics.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_basics/juce_gui_basics.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_extra/code_editor/juce_CodeDocument.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_extra/code_editor/juce_CodeEditorComponent.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_extra/code_editor/juce_CodeTokeniser.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_extra/code_editor/juce_CPlusPlusCodeTokeniser.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_extra/code_editor/juce_CPlusPlusCodeTokeniserFunctions.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_extra/code_editor/juce_LuaCodeTokeniser.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_extra/code_editor/juce_XMLCodeTokeniser.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_extra/documents/juce_FileBasedDocument.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_extra/embedding/juce_ActiveXControlComponent.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_extra/embedding/juce_NSViewComponent.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_extra/embedding/juce_UIViewComponent.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_extra/misc/juce_AnimatedAppComponent.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_extra/misc/juce_AppleRemote.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_extra/misc/juce_BubbleMessageComponent.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_extra/misc/juce_ColourSelector.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_extra/misc/juce_KeyMappingEditorComponent.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_extra/misc/juce_LiveConstantEditor.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_extra/misc/juce_PreferencesPanel.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_extra/misc/juce_RecentlyOpenedFilesList.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_extra/misc/juce_SplashScreen.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_extra/misc/juce_SystemTrayIconComponent.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_extra/misc/juce_WebBrowserComponent.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_extra/native/juce_mac_CarbonViewWrapperComponent.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_extra/juce_gui_extra.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_gui_extra/juce_gui_extra.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_opengl/geometry/juce_Draggable3DOrientation.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_opengl/geometry/juce_Matrix3D.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_opengl/geometry/juce_Quaternion.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_opengl/geometry/juce_Vector3D.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_opengl/native/juce_MissingGLDefinitions.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_opengl/native/juce_OpenGL_android.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_opengl/native/juce_OpenGL_ios.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_opengl/native/juce_OpenGL_linux.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_opengl/native/juce_OpenGL_osx.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_opengl/native/juce_OpenGL_win32.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_opengl/native/juce_OpenGLExtensions.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_opengl/opengl/juce_OpenGLContext.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_opengl/opengl/juce_OpenGLFrameBuffer.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_opengl/opengl/juce_OpenGLGraphicsContext.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_opengl/opengl/juce_OpenGLHelpers.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_opengl/opengl/juce_OpenGLImage.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_opengl/opengl/juce_OpenGLPixelFormat.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_opengl/opengl/juce_OpenGLRenderer.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_opengl/opengl/juce_OpenGLShaderProgram.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_opengl/opengl/juce_OpenGLTexture.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_opengl/utils/juce_OpenGLAppComponent.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_opengl/juce_opengl.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_opengl/juce_opengl.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_video/capture/juce_CameraDevice.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_video/playback/juce_DirectShowComponent.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_video/playback/juce_QuickTimeMovieComponent.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_video/juce_video.h" \
	"../../../../SDKs/JuceLibrary/4.3.1/modules/juce_video/juce_video.h" \
	"../../JuceLibraryCode/AppConfig.h" \
	"../../JuceLibraryCode/JuceHeader.h" \

